### PR TITLE
UI fixes

### PR DESCRIPTION
**Pull request by 0181532686cf4a31163be0bf3e6bb6732bf**
- Channels/params component
- Filtering (time and geo)
- Result labels
- No fix for session display yet (workaround: resize browser window or toggle drawing tools)

### CODE REVIEW

**Comment by landswellsong** [comment]
Issues encountered so far:
1. All of the parameters/channels are shown at once, the list should update with satellite selection. Parameters are per-satellite because channels are. Values (#178) should display like this, but that's a new iteration. 

2. Default selection is a `(41.33, 42,11) - (14.22, 17.31)` rectangle, but it's not shown as selection. It's extremely confusing as you start up, press search and only have a portion of data without any apparent filter until you notice.
image
Latitude and Longitude ranges in the manual entry box should have checkboxes (off by default).

3. If you don't do "Reset search" and just switch the satellite, the "Search" button stops working.

(not exhaustive, reloading with `origin` fixes)

**Comment by landswellsong** [comment]
4. Latitude/Longitude input boxes can't take negative values.

5. Search doesn't work well (maybe related to my yesterday's pull)
image

6. Searching Roundabout with Potential's parameter has a non-zero result (related to 1):
image
Yes, this is because we first look for sessions, but that's confusing never the less.

7. Same with parameter search:
image

8. Channel Quicklook gives a Parameter Quicklook. Test it with Roundabout Channel/Parameters, channels is microVolts, parameter is degrees Kelvin.

**Comment by landswellsong** [comment]
9. not related to the code of this PR, but I think the UX is overcomplicted. It needs to be rethinked completely, I think in vein of #115 

10. selection that wraps around the day change meridian seems not to work, will need more testing

**Comment by 0181532686cf4a31163be0bf3e6bb6732bf** [comment]
1. https://github.com/IonosatMicro/promis/blob/dev/backend/promis/backend_api/views.py#L71 . No any kind of `project` parameter there.
2. that was discussed with @elpiankova and whole team before;
5. ?
9. same

**Comment by landswellsong** [comment]
1. You can filter them out manually for now. Ideally I expected an issue to be created should this situation arise as opposed to silently displaying everything and not reporting a problem.
2. No, not really. If the initial screen is the initial filter then:
  - Initial values should be [-90°; 90°] x [-180°; 180] (i.e. the full map)
  - Switching to the map should display this as a selection rectangle.
This is as per discussion. Otherwise you hit search and you get a portion of the data without any visual cue why is that happening. Took me 5 minutes to figure out. It's way to confusing for the user, @elpiankova can back me up on this since I had to explain her what was happening.
3. Select a satellite, Search, select another Search. Poof! Nothing happens.
4. Try to enter -90 to the Latittude input.

**Comment by 0181532686cf4a31163be0bf3e6bb6732bf** [comment]
5. ?

**Comment by landswellsong** [comment]
Disregard 5 for now, I'll do more testing tomorrow on why that happens.

**Comment by landswellsong** [comment]
**Summarizing the acceptance criteria on this one**
WIthout creating separate issues:
- [x] The user must only see the channels / parameters belonging to the particular Space project (@lyssdod)
- [x] Default selection should be the whole map, other selections should be visualized (@landswellsong)
- [x] Search does not work when the map is on, rephrase of an earlier pt.3 after testing (~@lyssdod~ @landswellsong)
- [x] Can't enter negative values for latitudes / longitudes (@lyssdod)
- [ ] Check that the search operates correctly (@landswellsong)
- [x] Fix channel quicklooks which currently show parameter quicklooks instead (@lyssdod)
- [x] Display things on the map instantly without having to switch around (@landswellsong)

**Comment by landswellsong** [comment]
@lyssdod testing feedback:
1. Still can't enter negative lat/lng values by manually.
2. Quicklook seems fixed but switching the Channels/Parameters tab _after_ search replaces the names without replacing the quicklook. This should not happen, the UI is only for the selection criteria.
3. Confirming #226 as fixed

**Comment by 0181532686cf4a31163be0bf3e6bb6732bf** [comment]
Data picker is disabled when measurements are found. Leaving it enabled and allowing users to change query in place and thus making new API request each time control is changed may lead to backend overload by just fast clicking. Disabling it until user press 'Reset search' to pick new params.

**Review by landswellsong — APPROVED** [review]
lgtm

**Pull request merged**
