### PR TITLE
Power of 10 exponent to allow for unit prefixes

### PR DESCRIPTION
**Pull request by landswellsong**
Too tired to type an actual description, but you get the idea:

image
image
image

### CODE REVIEW

**Comment by 0181532686cf4a31163be0bf3e6bb6732bf** [comment]
Why it can not just return already processed units?

**Comment by landswellsong** [comment]
Can be done, just thought it'd be better for the client to render as unit prefixes or as 10-th exponent if they wish so. What do you think is better?

**Comment by 0181532686cf4a31163be0bf3e6bb6732bf** [comment]
I'd implement this in backend since units are configurable in admin/classes/etc. There's no need to process data twice.

**Comment by landswellsong** [comment]
Yeah ok, let me do this.

**Comment by landswellsong** [comment]
Does it look good now?

**Comment by 0181532686cf4a31163be0bf3e6bb6732bf** [comment]
Yes, that's better

**Review by 0181532686cf4a31163be0bf3e6bb6732bf — APPROVED** [review]

**Pull request merged**
